sudo: required

services:
  - docker

before_install:
  - echo "Logging in to Docker Hub"
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - echo "Logged in to Docker"
install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y python3 python3-pip
  - cd ./oven-app
  - sudo npm install -g aurelia-cli
  - npm install
  - cd ../

script:
  - cd ./oven-app
  - au build
  - cd ../

after_success:
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - export REPO=armedguy/oven
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO